# Generated by Django 3.2.21 on 2023-09-18 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Rubric',
                'verbose_name_plural': 'Rubric',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='db',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='db',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='db',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='db',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='db',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hello.rubric', verbose_name='Rubric'),
        ),
    ]
